#!/usr/bin/python3

def raise_exception_msg(message=""):
    """print raise a NameError with a message."""

    raise NameError(message)
